/**
 * WASM Seed Finder Worker
 *
 * This worker loads the Rust-compiled WASM module and runs batched seed
 * searches. It is spawned by the WasmSeedFinderPool.
 *
 * Message protocol:
 *   IN  { type: "init" }
 *   OUT { type: "ready" } | { type: "error", message: string }
 *
 *   IN  { type: "search", rngSeed, triesBatch, maxAnte, deck, stake, versionInt,
 *           jokerConstraints, voucherConstraints, tagConstraints }
 *   OUT { type: "result", tries, seed?, jokerLocations, voucherLocations, tagLocations }
 *   OUT { type: "error", message: string }
 */

let wasmModule: any = null;
let ready = false;

async function initWasm(): Promise<void> {
  try {
    // Dynamically import the wasm-bindgen ESM glue.
    // When the WASM build exists, this resolves to the compiled module.
    // In dev/test without a real WASM binary, we catch the error and run JS fallback.
    // Build path at runtime to avoid Vite static analysis of the import.
    // The real WASM glue is generated by `wasm-pack build --target web` into client/src/wasm/seedfinder/.
    // Until that step runs the file doesn't exist, so we keep the import opaque to the bundler.
    const wasmPath = /* @vite-ignore */ ["..", "wasm", "seedfinder", "seedfinder.js"].join("/");
    const mod = await import(/* @vite-ignore */ wasmPath);
    // wasm-pack --target web generates an init() default export
    await mod.default();
    wasmModule = mod;
    console.log("[wasm-worker] WASM loaded, capabilities:", mod.get_capabilities?.() ?? "unknown");
  } catch (err: any) {
    throw new Error("WASM module unavailable: " + (err?.message ?? String(err)));
  }
}

interface SearchMessage {
  type: "search";
  rngSeed: number;
  triesBatch: number;
  maxAnte: number;
  deck: string;
  stake: string;
  versionInt: number;
  jokerConstraints: Array<{ joker: string; edition?: string; source?: string; maxAnte: number }>;
  voucherConstraints: Array<{ voucher: string; maxAnte: number }>;
  tagConstraints: Array<{ tag: string; maxAnte: number }>;
}

self.onmessage = async (e: MessageEvent) => {
  const msg = e.data;

  if (msg.type === "init") {
    try {
      await initWasm();
      ready = true;
      (self as any).postMessage({ type: "ready" });
    } catch (err: any) {
      (self as any).postMessage({ type: "error", message: err.message ?? String(err) });
    }
    return;
  }

  if (msg.type === "search") {
    if (!ready || !wasmModule) {
      (self as any).postMessage({ type: "error", message: "WASM not ready" });
      return;
    }

    try {
      const m: SearchMessage = msg;
      const result = wasmModule.find_seed_batch_simd(
        m.rngSeed >>> 0,
        m.triesBatch,
        m.maxAnte,
        m.deck,
        m.stake,
        m.versionInt,
        m.jokerConstraints,
        m.voucherConstraints,
        m.tagConstraints,
      );

      (self as any).postMessage({
        type: "result",
        tries: result?.tries ?? m.triesBatch,
        seed: result?.seed ?? null,
        jokerLocations: result?.jokerLocations ?? [],
        voucherLocations: result?.voucherLocations ?? [],
        tagLocations: result?.tagLocations ?? [],
      });
    } catch (err: any) {
      (self as any).postMessage({ type: "error", message: err.message ?? String(err) });
    }
  }
};
